baseURL = 'https://nsd-singbar.ceo-suo.com/'
languageCode = 'ko-KR'
title = '낙성대 노래빠 라비: LAVI'

[params]
  isAdsEnabled = true
  adsTelegramId = "ggyuvely"

  description = '낙성대 노래빠 라비는 신림동 1432-73에 자리한 노래빠 매장으로, 봉천·낙성대에서 친구들과 노래방을 찾는 분들에게 알려져 있다.'
  author = '두리'
  datePublished = "2026-08-18T08:50:00+09:00"
  dateModified = "2026-08-18T08:50:00+09:00"
  [params.store]
	tel = "010-8306-5747"
  location = "낙성대"
	locationEn = "NSD"
  name = "라비"
	nameEn = "LAVI"
	nameIs = "는"
	category = "노래빠"
	categoryEn = "Singbar"
	categoryIs = "는"
	address = "서울 관악구"
	googleMapSrc = "https://www.google.com/maps?q=서울+관악구&output=embed"

enableRobotsTXT = false
cleanDestinationDir = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
